# Generated by Django 2.2.4 on 2020-07-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
